### ISSUE TITLE
Mac vs. Linux `join` behavior

### ISSUE THREAD

**Issue by patrickfuller** [numat/RASPA2#19]
From [this conversation](https://github.com/numat/RASPA2/commit/a55504e83f38cf2bddc575b4dd30e65b7e8ea03a), `process.join()` is behaving differently on different UNIX OS's.

The underlying reason for this should be researched. If needed, OS-specific `join` commands should be used.

**Comment by paulboone** [comment]
According to the python docs (https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process.join), the call `p.join(1)` on line 106 of raspa.py means that the join should timeout after 1 second. Is there a reason why the timeout is so small? It seems like it runs the entire simulation in that one process, so that means that if the timeout is enforced, it just completes as many cycles as it can before `p.terminate()` is called and kills the process.

This is my first time using RASPA (and looking at the code), but it seems like making the call `p.join()` with no argument so you wait forever would be the correct behavior.

**Comment by patrickfuller** [comment]
It makes sense to me. I'll update it and push a minor revision.

**Comment by patrickfuller** [comment]
Revised in 21a8c3f51c7c6247eaa7523f3333edb6fd2baea7, uploaded a revision bump to pypi. `pip install -U RASPA2` should work.
